# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\chart2_english.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1012, 611)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 581, 511))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 561, 411))
        self.label_2.setStyleSheet("\n"
"image: url(:/1/电机接线图1.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 460, 541, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(610, 20, 381, 511))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 30, 351, 461))
        self.label.setStyleSheet("\n"
"image: url(:/1/电机接口定义ENGLISH.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(909, 530, 81, 71))
        self.widget.setStyleSheet("QPushButton#pushButton{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 61, 51))
        self.pushButton.setStyleSheet("image: url(:/1/关闭.png);\n"
"QPushButton#pushButton{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Motor wiring diagram"))
        self.label_3.setText(_translate("Form", "Note: Pay attention to the number of subdivisions of the motor driver \n"
"when programming"))
        self.groupBox_2.setTitle(_translate("Form", "Motor interface definition"))
import text_rc
