# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\serial_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1900, 1008)
        self.textEdit_receive = QtWidgets.QTextEdit(Form)
        self.textEdit_receive.setGeometry(QtCore.QRect(900, 760, 561, 111))
        self.textEdit_receive.setObjectName("textEdit_receive")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(60, 10, 311, 301))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QPushButton#pushButton_save{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton_save:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_save:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}\n"
"QPushButton#pushButton_Open{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_Open:hover{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,111,219),stop:1 rgba(85,81,84,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_Open:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(150,123,111,125);\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton_ReceiveClean{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_ReceiveClean:hover{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,111,219),stop:1 rgba(85,81,84,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_ReceiveClean:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(150,123,111,125);\n"
"}\n"
"\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.comboBox_Com = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Com.setGeometry(QtCore.QRect(12, 27, 241, 40))
        self.comboBox_Com.setObjectName("comboBox_Com")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_Check = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Check.setGeometry(QtCore.QRect(105, 230, 151, 40))
        self.comboBox_Check.setStyleSheet("")
        self.comboBox_Check.setObjectName("comboBox_Check")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 80, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_Data = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Data.setGeometry(QtCore.QRect(105, 180, 151, 40))
        self.comboBox_Data.setObjectName("comboBox_Data")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_Stop = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Stop.setGeometry(QtCore.QRect(105, 130, 151, 40))
        self.comboBox_Stop.setObjectName("comboBox_Stop")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 80, 61, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox_Baud = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_Baud.setGeometry(QtCore.QRect(105, 80, 151, 40))
        self.comboBox_Baud.setObjectName("comboBox_Baud")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(-220, 50, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 10, 441, 981))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("\n"
"QPushButton#pushButton_show1_2,#pushButton_Send_2,#pushButton_SendClean_2,#pushButton_Send_3,#pushButton_SendClean_3,#pushButton_x1,#pushButton_x_0{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton_show1_2:hover,#pushButton_Send_2:hover,#pushButton_SendClean_2:hover,#pushButton_Send_3:hover,#pushButton_SendClean_3:hover,#pushButton_x1:hover,#pushButton_x_0:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_show1_2:pressed,#pushButton_Send_2:pressed,#pushButton_SendClean_2:pressed,#pushButton_Send_3:pressed,#pushButton_SendClean_3:pressed,#pushButton_x1:pressed,#pushButton_x_0:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton_kaishi{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton_kaishi:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_kaishi:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}\n"
"\n"
"QPushButton#pushButton_Open{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_Open:hover{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,111,219),stop:1 rgba(85,81,84,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_Open:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(150,123,111,125);\n"
"}\n"
"\n"
"QPushButton#pushButton_Send_load{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton_Send_load:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_Send_load:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}\n"
"\n"
"QPushButton#pushButton_SendClean_load{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton_SendClean_load:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_SendClean_load:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}\n"
"\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_Send_4 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_Send_4.setGeometry(QtCore.QRect(100, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_Send_4.setFont(font)
        self.textEdit_Send_4.setObjectName("textEdit_Send_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(30, 90, 51, 37))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_kaishi = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_kaishi.setGeometry(QtCore.QRect(210, 810, 221, 201))
        self.pushButton_kaishi.setStyleSheet("image: url(:/1/开始 (1).png);")
        self.pushButton_kaishi.setText("")
        self.pushButton_kaishi.setObjectName("pushButton_kaishi")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 130, 421, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_x1 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_x1.setGeometry(QtCore.QRect(240, 20, 101, 100))
        self.pushButton_x1.setStyleSheet("image: url(:/1/左旋转 (1).png);")
        self.pushButton_x1.setText("")
        self.pushButton_x1.setObjectName("pushButton_x1")
        self.pushButton_x_0 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_x_0.setGeometry(QtCore.QRect(40, 20, 101, 100))
        self.pushButton_x_0.setStyleSheet("image: url(:/1/右旋转.png);")
        self.pushButton_x_0.setText("")
        self.pushButton_x_0.setObjectName("pushButton_x_0")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(200, 100, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 260, 421, 311))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("QPushButton#pushButton_SendClean_speed,#pushButton_SendClean_radius,#pushButton_Send_speed,#pushButton_Send_r{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton_SendClean_speed:hover,#pushButton_SendClean_radius:hover,#pushButton_Send_speed:hover,#pushButton_Send_r:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_SendClean_speed:pressed,#pushButton_SendClean_radius:pressed,#pushButton_Send_speed:pressed,#pushButton_Send_r:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_8)
        self.label_8.setGeometry(QtCore.QRect(20, 175, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_8)
        self.textEdit.setGeometry(QtCore.QRect(90, 171, 81, 31))
        self.textEdit.setObjectName("textEdit")
        self.label_13 = QtWidgets.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(180, 181, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(20, 261, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(180, 270, 31, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_8)
        self.textEdit_2.setGeometry(QtCore.QRect(90, 260, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_SendClean_speed = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_SendClean_speed.setGeometry(QtCore.QRect(340, 150, 71, 71))
        self.pushButton_SendClean_speed.setStyleSheet("image: url(:/1/清楚缓存.png);\n"
"image: url(:/1/清楚缓存 (1).png);")
        self.pushButton_SendClean_speed.setText("")
        self.pushButton_SendClean_speed.setObjectName("pushButton_SendClean_speed")
        self.pushButton_SendClean_radius = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_SendClean_radius.setGeometry(QtCore.QRect(340, 240, 71, 71))
        self.pushButton_SendClean_radius.setStyleSheet("image: url(:/1/清楚缓存.png);\n"
"image: url(:/1/清楚缓存 (1).png);")
        self.pushButton_SendClean_radius.setText("")
        self.pushButton_SendClean_radius.setObjectName("pushButton_SendClean_radius")
        self.pushButton_Send_speed = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_Send_speed.setGeometry(QtCore.QRect(240, 150, 71, 71))
        self.pushButton_Send_speed.setStyleSheet("image: url(:/1/发送 (2).png);")
        self.pushButton_Send_speed.setText("")
        self.pushButton_Send_speed.setObjectName("pushButton_Send_speed")
        self.pushButton_Send_r = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_Send_r.setGeometry(QtCore.QRect(240, 240, 71, 71))
        self.pushButton_Send_r.setStyleSheet("image: url(:/1/发送 (2).png);")
        self.pushButton_Send_r.setText("")
        self.pushButton_Send_r.setObjectName("pushButton_Send_r")
        self.checkBox_speed = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_speed.setGeometry(QtCore.QRect(20, 120, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.checkBox_speed.setFont(font)
        self.checkBox_speed.setObjectName("checkBox_speed")
        self.textEdit_Send_2 = QtWidgets.QTextEdit(self.groupBox_8)
        self.textEdit_Send_2.setGeometry(QtCore.QRect(20, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_Send_2.setFont(font)
        self.textEdit_Send_2.setObjectName("textEdit_Send_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_8)
        self.label_11.setGeometry(QtCore.QRect(160, 65, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.pushButton_Send_2 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_Send_2.setGeometry(QtCore.QRect(240, 35, 71, 71))
        self.pushButton_Send_2.setStyleSheet("image: url(:/1/发送 (2).png);")
        self.pushButton_Send_2.setText("")
        self.pushButton_Send_2.setObjectName("pushButton_Send_2")
        self.pushButton_SendClean_2 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_SendClean_2.setGeometry(QtCore.QRect(340, 35, 71, 71))
        self.pushButton_SendClean_2.setStyleSheet("image: url(:/1/清楚缓存.png);\n"
"image: url(:/1/清楚缓存 (1).png);")
        self.pushButton_SendClean_2.setText("")
        self.pushButton_SendClean_2.setObjectName("pushButton_SendClean_2")
        self.checkBox_speed_2 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_speed_2.setGeometry(QtCore.QRect(20, 30, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.checkBox_speed_2.setFont(font)
        self.checkBox_speed_2.setObjectName("checkBox_speed_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 580, 421, 131))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QPushButton#pushButton_SendClean_3,#pushButton_Send_3{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton_SendClean_3:hover,#pushButton_Send_3:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_SendClean_3:pressed,#pushButton_Send_3:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit_Send_3 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_Send_3.setGeometry(QtCore.QRect(89, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_Send_3.setFont(font)
        self.textEdit_Send_3.setObjectName("textEdit_Send_3")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(190, 90, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.pushButton_Send_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_Send_3.setGeometry(QtCore.QRect(220, 20, 91, 91))
        self.pushButton_Send_3.setStyleSheet("image: url(:/1/开始.png);")
        self.pushButton_Send_3.setText("")
        self.pushButton_Send_3.setObjectName("pushButton_Send_3")
        self.pushButton_SendClean_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_SendClean_3.setGeometry(QtCore.QRect(340, 30, 71, 71))
        self.pushButton_SendClean_3.setStyleSheet("image: url(:/1/清楚缓存.png);\n"
"image: url(:/1/清楚缓存 (1).png);")
        self.pushButton_SendClean_3.setText("")
        self.pushButton_SendClean_3.setObjectName("pushButton_SendClean_3")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(20, 35, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setGeometry(QtCore.QRect(20, 85, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.textEdit_Send_5 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_Send_5.setGeometry(QtCore.QRect(90, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_Send_5.setFont(font)
        self.textEdit_Send_5.setObjectName("textEdit_Send_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 720, 421, 121))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("QPushButton#pushButton_Send{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton_Send:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_Send:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}\n"
"\n"
"QPushButton#pushButton_Send,#pushButton_SendClean{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButtonpushButton_SendClean:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_SendClean:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_SendClean = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_SendClean.setGeometry(QtCore.QRect(340, 50, 71, 71))
        self.pushButton_SendClean.setStyleSheet("image: url(:/1/清楚缓存 (1).png);")
        self.pushButton_SendClean.setText("")
        self.pushButton_SendClean.setObjectName("pushButton_SendClean")
        self.textEdit_Send = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_Send.setGeometry(QtCore.QRect(20, 60, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_Send.setFont(font)
        self.textEdit_Send.setObjectName("textEdit_Send")
        self.checkBox_threshold = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_threshold.setGeometry(QtCore.QRect(20, 20, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.checkBox_threshold.setFont(font)
        self.checkBox_threshold.setObjectName("checkBox_threshold")
        self.pushButton_Send = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_Send.setGeometry(QtCore.QRect(240, 50, 71, 71))
        font = QtGui.QFont()
        font.setFamily("3DS Fonticon")
        self.pushButton_Send.setFont(font)
        self.pushButton_Send.setStyleSheet("image: url(:/1/发送 (2).png);")
        self.pushButton_Send.setText("")
        self.pushButton_Send.setObjectName("pushButton_Send")
        self.pushButton_show1_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_show1_2.setGeometry(QtCore.QRect(30, 890, 81, 81))
        self.pushButton_show1_2.setStyleSheet("image: url(:/1/急停.png);")
        self.pushButton_show1_2.setText("")
        self.pushButton_show1_2.setObjectName("pushButton_show1_2")
        self.pushButton_Open = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Open.setEnabled(True)
        self.pushButton_Open.setGeometry(QtCore.QRect(10, 30, 201, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Open.setFont(font)
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.pushButton_Send_load = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Send_load.setGeometry(QtCore.QRect(240, 70, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Send_load.setFont(font)
        self.pushButton_Send_load.setStyleSheet("image: url(:/1/发送 (2).png);")
        self.pushButton_Send_load.setText("")
        self.pushButton_Send_load.setObjectName("pushButton_Send_load")
        self.pushButton_SendClean_load = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_SendClean_load.setGeometry(QtCore.QRect(350, 70, 71, 71))
        self.pushButton_SendClean_load.setStyleSheet("image: url(:/1/清楚缓存.png);\n"
"image: url(:/1/清楚缓存 (1).png);")
        self.pushButton_SendClean_load.setText("")
        self.pushButton_SendClean_load.setObjectName("pushButton_SendClean_load")
        self.pushButton_kaishi.raise_()
        self.textEdit_Send_4.raise_()
        self.label_9.raise_()
        self.groupBox_7.raise_()
        self.label_17.raise_()
        self.groupBox_8.raise_()
        self.groupBox_3.raise_()
        self.groupBox_5.raise_()
        self.pushButton_show1_2.raise_()
        self.pushButton_Open.raise_()
        self.pushButton_Send_load.raise_()
        self.pushButton_SendClean_load.raise_()
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(900, 730, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(10, 330, 391, 311))
        self.label_10.setStyleSheet("image: url(:/1/图片1.1.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(850, 20, 1031, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(900, 700, 951, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar { border: 2px solid grey; border-radius: 5px; color: rgb(20,20,20);  background-color: #FFFFFF; text-align: center;}QProgressBar::chunk {background-color: rgb(100,200,200); border-radius: 10px; margin: 0.1px;  width: 1px;}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(900, 970, 731, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textEdit_receive_data = QtWidgets.QTextEdit(Form)
        self.textEdit_receive_data.setGeometry(QtCore.QRect(900, 900, 121, 71))
        self.textEdit_receive_data.setObjectName("textEdit_receive_data")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(900, 875, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 680, 341, 311))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QPushButton#pushButton_show2{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_show2:hover{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,111,219),stop:1 rgba(85,81,84,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_show2:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(150,123,111,125);\n"
"}\n"
"\n"
"QPushButton#pushButton_show2_stop{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_show2_stop:hover{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,111,219),stop:1 rgba(85,81,84,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_show2_stop:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(150,123,111,125);\n"
"}\n"
"\n"
"QPushButton#pushButton_show_bujin{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_show_bujin:hover{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,111,219),stop:1 rgba(85,81,84,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_show_bujin:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(150,123,111,125);\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton_show_chart3{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_show_chart3:hover{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,111,219),stop:1 rgba(85,81,84,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_show_chart3:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(150,123,111,125);\n"
"}\n"
"\n"
"QPushButton#pushButton_ch{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_ch:hover{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,111,219),stop:1 rgba(85,81,84,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_ch:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(150,123,111,125);\n"
"}\n"
"")
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_show2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_show2.setGeometry(QtCore.QRect(40, 30, 261, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_show2.setFont(font)
        self.pushButton_show2.setObjectName("pushButton_show2")
        self.pushButton_show_bujin = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_show_bujin.setGeometry(QtCore.QRect(40, 240, 261, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_show_bujin.setFont(font)
        self.pushButton_show_bujin.setObjectName("pushButton_show_bujin")
        self.pushButton_show_chart3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_show_chart3.setGeometry(QtCore.QRect(40, 170, 261, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_show_chart3.setFont(font)
        self.pushButton_show_chart3.setObjectName("pushButton_show_chart3")
        self.pushButton_show2_stop = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_show2_stop.setGeometry(QtCore.QRect(40, 100, 261, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_show2_stop.setFont(font)
        self.pushButton_show2_stop.setObjectName("pushButton_show2_stop")
        self.groupBox_10 = QtWidgets.QGroupBox(Form)
        self.groupBox_10.setGeometry(QtCore.QRect(1480, 740, 391, 261))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("QPushButton#pushButton_save{\n"
"  background-color:rgba(0,0,0,0);\n"
"  color:rgba(85,98,112,255);\n"
"} \n"
"QPushButton#pushButton_save:hover{\n"
"  color:rgba(131,96,53,255);\n"
"} \n"
"QPushButton#pushButton_save:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  color:rgba(91,88,53,255);\n"
"}\n"
"\n"
"\n"
"QPushButton#pushButton_ReceiveClean{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(11,131,120,219),stop:1 rgba(85,98,112,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_ReceiveClean:hover{\n"
"  background-color:qlineargradient(spread:pad,x1:0,y1:0.505682,x2:1,y2:0.477,stop:0 rgba(150,123,111,219),stop:1 rgba(85,81,84,226));\n"
"  color:rgba(255,255,255,210);\n"
"  border-radius:5px;\n"
"} \n"
"QPushButton#pushButton_ReceiveClean:pressed{\n"
"  padding-left:5px;\n"
"  padding-top:5px;\n"
"  background-color:rgba(150,123,111,125);\n"
"}\n"
"")
        self.groupBox_10.setObjectName("groupBox_10")
        self.pushButton_ReceiveClean = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_ReceiveClean.setGeometry(QtCore.QRect(50, 30, 291, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ReceiveClean.setFont(font)
        self.pushButton_ReceiveClean.setObjectName("pushButton_ReceiveClean")
        self.label_15 = QtWidgets.QLabel(self.groupBox_10)
        self.label_15.setGeometry(QtCore.QRect(90, 170, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_save.setGeometry(QtCore.QRect(160, 120, 211, 121))
        self.pushButton_save.setStyleSheet("image: url(:/1/保存.png);\n"
"image: url(:/1/保存.png);")
        self.pushButton_save.setText("")
        self.pushButton_save.setObjectName("pushButton_save")
        self.textEdit_receive_data_xishu = QtWidgets.QTextEdit(Form)
        self.textEdit_receive_data_xishu.setGeometry(QtCore.QRect(1050, 940, 151, 31))
        self.textEdit_receive_data_xishu.setObjectName("textEdit_receive_data_xishu")
        self.textEdit_receive_data_min = QtWidgets.QTextEdit(Form)
        self.textEdit_receive_data_min.setGeometry(QtCore.QRect(1050, 900, 91, 31))
        self.textEdit_receive_data_min.setObjectName("textEdit_receive_data_min")
        self.textEdit_receive_data_max = QtWidgets.QTextEdit(Form)
        self.textEdit_receive_data_max.setGeometry(QtCore.QRect(1150, 900, 91, 31))
        self.textEdit_receive_data_max.setObjectName("textEdit_receive_data_max")
        self.textEdit_receive_data_mean = QtWidgets.QTextEdit(Form)
        self.textEdit_receive_data_mean.setGeometry(QtCore.QRect(1250, 900, 91, 31))
        self.textEdit_receive_data_mean.setObjectName("textEdit_receive_data_mean")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(1050, 880, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(1150, 880, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(1250, 880, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.action12 = QtWidgets.QAction(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../pyqt5 - 副本/stop.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action12.setIcon(icon)
        self.action12.setObjectName("action12")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "COM"))
        self.label_4.setText(_translate("Form", "Check bit"))
        self.label_3.setText(_translate("Form", "Data bit"))
        self.label_2.setText(_translate("Form", "Stop bit"))
        self.label.setText(_translate("Form", "Baud     "))
        self.groupBox_2.setTitle(_translate("Form", "The operation setting"))
        self.label_9.setText(_translate("Form", "Load:"))
        self.groupBox_7.setTitle(_translate("Form", "Direction of rotation"))
        self.label_17.setText(_translate("Form", "N"))
        self.groupBox_8.setTitle(_translate("Form", "Speed"))
        self.label_8.setText(_translate("Form", "Speed :"))
        self.label_13.setText(_translate("Form", "cm/s"))
        self.label_14.setText(_translate("Form", "Radius:"))
        self.label_16.setText(_translate("Form", "mm"))
        self.checkBox_speed.setText(_translate("Form", "linear speed"))
        self.label_11.setText(_translate("Form", "r/min"))
        self.checkBox_speed_2.setText(_translate("Form", "rotate"))
        self.groupBox_3.setTitle(_translate("Form", "Time"))
        self.label_12.setText(_translate("Form", "min"))
        self.label_18.setText(_translate("Form", "Cycles:"))
        self.label_23.setText(_translate("Form", "Time:"))
        self.groupBox_5.setTitle(_translate("Form", "Threshold"))
        self.checkBox_threshold.setText(_translate("Form", "friction coefficient threshold"))
        self.pushButton_Open.setText(_translate("Form", "Open the serial port"))
        self.label_6.setText(_translate("Form", "The operation setting display"))
        self.label_7.setText(_translate("Form", "*Note that whether you choose rotate or linear speed, the half pulse frequency must be an integer！"))
        self.label_19.setText(_translate("Form", "Data display"))
        self.groupBox_4.setTitle(_translate("Form", "Help"))
        self.pushButton_show2.setText(_translate("Form", "Start of signal \n"
"calibration"))
        self.pushButton_show_bujin.setText(_translate("Form", "Motor driver"))
        self.pushButton_show_chart3.setText(_translate("Form", "Transducer"))
        self.pushButton_show2_stop.setText(_translate("Form", "End of signal \n"
"calibration"))
        self.groupBox_10.setTitle(_translate("Form", "The other operation setting"))
        self.pushButton_ReceiveClean.setText(_translate("Form", "Clear the receiving"))
        self.label_15.setText(_translate("Form", "Save"))
        self.label_20.setText(_translate("Form", "Min"))
        self.label_21.setText(_translate("Form", "Max"))
        self.label_22.setText(_translate("Form", "Mean"))
        self.action12.setText(_translate("Form", "12"))
import text_rc
